import Head from 'next/head'
// import Image from 'next/image'
// import { Inter } from '@next/font/google'

// const inter = Inter({ subsets: ['latin'] })
import Header from '@/components/Header'
import Banner from '@/components/Banner'
import Smallinfo from '@/components/smallinfo'
import InfoCard from '@/components/InfoCard'
import ReviseBanner from '@/components/ReviseBanner'

export default function Home() {
  return (
    <>
      <Head>
        <title>Gym baran</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
{/* bg-gradient-to-r from-[#d388ff15] to-white bg-[#d388ff15] */}

      </Head>
      <main className=' max-w-[1236px] mx-auto bg-gradient'>
        <div className=''>
          <Header></Header>
          <Banner></Banner>
          <Smallinfo></Smallinfo>
          <InfoCard></InfoCard>
          <ReviseBanner></ReviseBanner>
        </div>
      </main>

    </>
  )
}
